# docker-compose.yml (Versão com persistência de dados para o Grafana)

services:
  # Serviço do Robô Analisador
  fib-scanner:
    build: .
    container_name: fib-scanner
    restart: unless-stopped
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    ports:
      - "8000:8000" # Expõe a porta para o Prometheus

  # Serviço do Prometheus para coletar métricas
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - fib-scanner

  # Serviço do Grafana para visualizar os dados
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana # <-- LINHA ADICIONADA PARA PERSISTÊNCIA
    depends_on:
      - prometheus

# Definição do volume nomeado para o Grafana
volumes:
  grafana-data: # <-- SEÇÃO ADICIONADA PARA CRIAR O VOLUME
