# docker-compose.yml (Versão 3.0 - Final e Integrada)
version: '3.8'

services:
  robot:
    build: .
    container_name: trading_robot
    restart: unless-stopped
    env_file:
      - .env  # Carrega as variáveis do .env de forma segura
    volumes:
      - ./logs:/app/logs  # Mapeia a pasta de logs para o host E para o container
    networks:
      - monitor-net

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./logs:/var/log/robot  # Mapeia a pasta de logs do host para o Promtail ler
      - ./promtail-config.yml:/etc/promtail/config.yml # Mapeia o arquivo de configuração do Promtail
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitor-net
    depends_on:
      - robot # Garante que o robô inicie antes do Promtail

  loki:
    image: grafana/loki:latest
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    restart: unless-stopped
    networks:
      - monitor-net

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitor-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitor-net

volumes:
  grafana-data:

networks:
  monitor-net:
    driver: bridge
