# promtail-config.yml
server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: robot-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: robot_errors # Label para os logs de erro
          __path__: /var/log/robot/error.log
      - targets:
          - localhost
        labels:
          job: robot_trades # Label para o histórico de trades
          __path__: /var/log/robot/trade_history.csv
