global:
  scrape_interval: 15s # A cada 15 segundos, o Prometheus vai coletar as métricas

scrape_configs:
  - job_name: 'fib-scanner'
    static_configs:
      - targets: ['fib-scanner:8000'] # O nome do serviço e a porta que definimos no nosso robô
